# Generated by Django 2.2.2 on 2019-06-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='imagen',
            field=models.ImageField(default='images/none/no-img.jpg', upload_to='images/'),
        ),
    ]
