# Generated by Django 2.2.2 on 2019-06-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_entradas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
