# Generated by Django 2.2.2 on 2019-06-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_entradas_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
