# Generated by Django 2.2.2 on 2019-06-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190616_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
